import { Suspense } from 'react';
import '../globals.css';
import Tracker from '@/src/components/tracker';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Tracker />
        <Suspense>
          {children}
        </Suspense>
      </body>
    </html>
  )
}
